export const strings = {
  siteName: "flinkbase",
  siteTagline: "AI News. 3x am Tag. Auf Deutsch.",
  siteDescription: "Deutschsprachiger AI News Digest — die wichtigsten KI-Nachrichten von Hacker News, 3x täglich zusammengefasst und eingeordnet.",
  heroSubline: "Die wichtigsten KI-Nachrichten, 3x täglich kondensiert und eingeordnet. Kein Noise, nur Signal.",
  newsletterTitle: "Kein Digest verpassen",
  newsletterPlaceholder: "deine@email.de",
  newsletterButton: "Eintragen",
  newsletterDisclaimer: "Kein Spam. Jederzeit abmeldbar.",
  archivTitle: "Archiv",
  searchTitle: "Suche",
  searchPlaceholder: "AI-Thema suchen...",
  searchButton: "Suchen",
  aboutTitle: "Über flinkbase",
  imprintTitle: "Impressum",
  privacyTitle: "Datenschutz",
  whyRelevantLabel: "Warum wichtig",
  dayInsightLabel: "Einordnung",
  prevDigest: "← Vorheriger Digest",
  nextDigest: "Nächster Digest →",
  noResults: "Keine Ergebnisse gefunden.",
  paywallTitle: "Archiv nur für Abonnenten",
  paywallText: "Dieser Digest ist älter als 7 Tage. Das vollständige Archiv ist bald als Abo verfügbar.",
  slotLabels: { morgen: "Morgen", mittag: "Mittag", abend: "Abend" } as Record<string, string>,
  termsTitle: "Nutzungsbedingungen",
  footer: "© flinkbase. AI News Digest.",
} as const;
